# Generated by Django 3.1.5 on 2021-01-23 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField(verbose_name='Write your Question Here!!')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('question_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_asker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ans', to='App_Articles.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-answer_date',),
            },
        ),
    ]
