# Generated by Django 3.1.5 on 2021-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Articles', '0002_answerquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(blank=True, max_length=264, verbose_name='Put a Title'),
        ),
    ]
