# Generated by Django 3.1.5 on 2021-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user_type',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
