# Generated by Django 3.1.5 on 2021-01-22 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_auto_20210122_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
